select:
  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_4} termostat lås"
    id: thermostat_lock_channel_4
    address: 420
    force_new_range: true
    use_write_multiple: true
    value_type: U_WORD
    optionsmap:
      "Locked" : 8
      "Hotel" : 16
      "Unlocked" : 32
      
#########################
#### INPUT REGISTER  ####
#########################
sensor:

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_4} mode"
    id: mode_channel_4
    register_type: read
    address: 402
      
  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_4} temperatur"
    id: temperatur_channel_4
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    register_type: read
    address: 404
    filters:
      - multiply: 0.01
      
  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_4} luftfugtighed"
    id: luftfugtighed_channel_4
    unit_of_measurement: '%'
    accuracy_decimals: 1
    device_class: humidity
    register_type: read
    address: 406
    filters:
      - multiply: 0.01 

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_4} dugpunkt"
    id: dugpunkt_channel_4
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: humidity
    register_type: read
    address: 407
    filters:
      - multiply: 0.01  
      
#########################
### SETPOINT REGISTER  ##
#########################
number:

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_4} temperatur setpunkt"
    id: temperatur_setpunkt_channel_4
    min_value: 10.0
    max_value: 30.0
    step: 0.5
    address: 419
    force_new_range: true
    use_write_multiple: true 
    multiply: 100  

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_4} ferie temperatur setpunkt"
    id: ferie_temperatur_setpunkt_channel_4
    min_value: 10.0
    max_value: 30.0
    step: 0.5
    address: 422
    force_new_range: true
    use_write_multiple: true 
    multiply: 100

#########################
#### INPUT REGISTER  ####
#########################
binary_sensor:

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "Fejl ${channel_4}"
    id: sentio_warning_channel_4
    register_type: read
    address: 401
    bitmask: 1      

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "Lav batteri ${channel_4}"
    id: sentio_battery_low_channel_4
    register_type: read
    address: 403
    bitmask: 1 

#########################
#### CLIMATE ENTITY   ###
#########################
climate:
  - platform: sentio
    name: ${channel_4}
    current_temp_sensor_id: temperatur_channel_4
    target_temp_sensor_id: temperatur_setpunkt_channel_4
    mode_select_id: mode_channel_4