select:
  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_7} termostat lås"
    id: thermostat_lock_channel_7
    address: 720
    force_new_range: true
    use_write_multiple: true
    value_type: U_WORD
    optionsmap:
      "Locked" : 8
      "Hotel" : 16
      "Unlocked" : 32
      
#########################
#### INPUT REGISTER  ####
#########################
sensor:

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_7} mode"
    id: mode_channel_7
    register_type: read
    address: 702
      
  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_7} temperatur"
    id: temperatur_channel_7
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    register_type: read
    address: 704
    filters:
      - multiply: 0.01
      
  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_7} luftfugtighed"
    id: luftfugtighed_channel_7
    unit_of_measurement: '%'
    accuracy_decimals: 1
    device_class: humidity
    register_type: read
    address: 706
    filters:
      - multiply: 0.01 

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_7} dugpunkt"
    id: dugpunkt_channel_7
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: humidity
    register_type: read
    address: 707
    filters:
      - multiply: 0.01  
      
#########################
### SETPOINT REGISTER  ##
#########################
number:

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_7} temperatur setpunkt"
    id: temperatur_setpunkt_channel_7
    min_value: 10.0
    max_value: 30.0
    step: 0.5
    address: 719
    force_new_range: true
    use_write_multiple: true 
    multiply: 100  

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_7} ferie temperatur setpunkt"
    id: ferie_temperatur_setpunkt_channel_7
    min_value: 10.0
    max_value: 30.0
    step: 0.5
    address: 722
    force_new_range: true
    use_write_multiple: true 
    multiply: 100

#########################
#### INPUT REGISTER  ####
#########################
binary_sensor:

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "Fejl ${channel_7}"
    id: sentio_warning_channel_7
    register_type: read
    address: 701
    bitmask: 1      

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "Lav batteri ${channel_7}"
    id: sentio_battery_low_channel_7
    register_type: read
    address: 703
    bitmask: 1 

#########################
#### CLIMATE ENTITY   ###
#########################
climate:
  - platform: sentio
    name: ${channel_7}
    current_temp_sensor_id: temperatur_channel_7
    target_temp_sensor_id: temperatur_setpunkt_channel_7
    mode_select_id: mode_channel_7