select:
  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_5} termostat lås"
    id: thermostat_lock_channel_5
    address: 520
    force_new_range: true
    use_write_multiple: true
    value_type: U_WORD
    optionsmap:
      "Locked" : 8
      "Hotel" : 16
      "Unlocked" : 32
      
#########################
#### INPUT REGISTER  ####
#########################
sensor:

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_5} mode"
    id: mode_channel_5
    register_type: read
    address: 502
      
  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_5} temperatur"
    id: temperatur_channel_5
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    register_type: read
    address: 504
    filters:
      - multiply: 0.01
      
  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_5} luftfugtighed"
    id: luftfugtighed_channel_5
    unit_of_measurement: '%'
    accuracy_decimals: 1
    device_class: humidity
    register_type: read
    address: 506
    filters:
      - multiply: 0.01 

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_5} dugpunkt"
    id: dugpunkt_channel_5
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: humidity
    register_type: read
    address: 507
    filters:
      - multiply: 0.01  
      
#########################
### SETPOINT REGISTER  ##
#########################
number:

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_5} temperatur setpunkt"
    id: temperatur_setpunkt_channel_5
    min_value: 10.0
    max_value: 30.0
    step: 0.5
    address: 519
    force_new_range: true
    use_write_multiple: true 
    multiply: 100  

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_5} ferie temperatur setpunkt"
    id: ferie_temperatur_setpunkt_channel_5
    min_value: 10.0
    max_value: 30.0
    step: 0.5
    address: 522
    force_new_range: true
    use_write_multiple: true 
    multiply: 100

#########################
#### INPUT REGISTER  ####
#########################
binary_sensor:

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "Fejl ${channel_5}"
    id: sentio_warning_channel_5
    register_type: read
    address: 501
    bitmask: 1      

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "Lav batteri ${channel_5}"
    id: sentio_battery_low_channel_5
    register_type: read
    address: 503
    bitmask: 1 

#########################
#### CLIMATE ENTITY   ###
#########################
climate:
  - platform: sentio
    name: ${channel_5}
    current_temp_sensor_id: temperatur_channel_5
    target_temp_sensor_id: temperatur_setpunkt_channel_5
    mode_select_id: mode_channel_5