select:
  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_9} termostat lås"
    id: thermostat_lock_channel_9
    address: 920
    force_new_range: true
    use_write_multiple: true
    value_type: U_WORD
    optionsmap:
      "Locked" : 8
      "Hotel" : 16
      "Unlocked" : 32
      
#########################
#### INPUT REGISTER  ####
#########################
sensor:

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_9} mode"
    id: mode_channel_9
    register_type: read
    address: 902
      
  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_9} temperatur"
    id: temperatur_channel_9
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    register_type: read
    address: 904
    filters:
      - multiply: 0.01
      
  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_9} luftfugtighed"
    id: luftfugtighed_channel_9
    unit_of_measurement: '%'
    accuracy_decimals: 1
    device_class: humidity
    register_type: read
    address: 906
    filters:
      - multiply: 0.01 

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_9} dugpunkt"
    id: dugpunkt_channel_9
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: humidity
    register_type: read
    address: 907
    filters:
      - multiply: 0.01  
      
#########################
### SETPOINT REGISTER  ##
#########################
number:

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_9} temperatur setpunkt"
    id: temperatur_setpunkt_channel_9
    min_value: 10.0
    max_value: 30.0
    step: 0.5
    address: 919
    force_new_range: true
    use_write_multiple: true 
    multiply: 100  

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_9} ferie temperatur setpunkt"
    id: ferie_temperatur_setpunkt_channel_9
    min_value: 10.0
    max_value: 30.0
    step: 0.5
    address: 922
    force_new_range: true
    use_write_multiple: true 
    multiply: 100

#########################
#### INPUT REGISTER  ####
#########################
binary_sensor:

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "Fejl ${channel_9}"
    id: sentio_warning_channel_9
    register_type: read
    address: 901
    bitmask: 1      

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "Lav batteri ${channel_9}"
    id: sentio_battery_low_channel_9
    register_type: read
    address: 903
    bitmask: 1 

#########################
#### CLIMATE ENTITY   ###
#########################
climate:
  - platform: sentio
    name: ${channel_9}
    current_temp_sensor_id: temperatur_channel_9
    target_temp_sensor_id: temperatur_setpunkt_channel_9
    mode_select_id: mode_channel_9