select:
  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_15} termostat lås"
    id: thermostat_lock_channel_15
    address: 1520
    force_new_range: true
    use_write_multiple: true
    value_type: U_WORD
    optionsmap:
      "Locked" : 8
      "Hotel" : 16
      "Unlocked" : 32
      
#########################
#### INPUT REGISTER  ####
#########################
sensor:

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_15} mode"
    id: mode_channel_15
    register_type: read
    address: 1502
      
  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_15} temperatur"
    id: temperatur_channel_15
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    register_type: read
    address: 1504
    filters:
      - multiply: 0.01
      
  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_15} luftfugtighed"
    id: luftfugtighed_channel_15
    unit_of_measurement: '%'
    accuracy_decimals: 1
    device_class: humidity
    register_type: read
    address: 1506
    filters:
      - multiply: 0.01 

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_15} dugpunkt"
    id: dugpunkt_channel_15
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: humidity
    register_type: read
    address: 1507
    filters:
      - multiply: 0.01  
      
#########################
### SETPOINT REGISTER  ##
#########################
number:

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_15} temperatur setpunkt"
    id: temperatur_setpunkt_channel_15
    min_value: 10.0
    max_value: 30.0
    step: 0.5
    address: 1519
    force_new_range: true
    use_write_multiple: true 
    multiply: 100  

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_15} ferie temperatur setpunkt"
    id: ferie_temperatur_setpunkt_channel_15
    min_value: 10.0
    max_value: 30.0
    step: 0.5
    address: 1522
    force_new_range: true
    use_write_multiple: true 
    multiply: 100

#########################
#### INPUT REGISTER  ####
#########################
binary_sensor:

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "Fejl ${channel_15}"
    id: sentio_warning_channel_15
    register_type: read
    address: 1501
    bitmask: 1      

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "Lav batteri ${channel_15}"
    id: sentio_battery_low_channel_15
    register_type: read
    address: 1503
    bitmask: 1 

#########################
#### CLIMATE ENTITY   ###
#########################
climate:
  - platform: sentio
    name: ${channel_15}
    current_temp_sensor_id: temperatur_channel_15
    target_temp_sensor_id: temperatur_setpunkt_channel_15
    mode_select_id: mode_channel_15