select:
  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_2} termostat lås"
    id: thermostat_lock_channel_2
    address: 220
    force_new_range: true
    use_write_multiple: true
    value_type: U_WORD
    optionsmap:
      "Locked" : 8
      "Hotel" : 16
      "Unlocked" : 32
      
#########################
#### INPUT REGISTER  ####
#########################
sensor:

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_2} mode"
    id: mode_channel_2
    register_type: read
    address: 202
      
  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_2} temperatur"
    id: temperatur_channel_2
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    register_type: read
    address: 204
    filters:
      - multiply: 0.01
      
  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_2} luftfugtighed"
    id: luftfugtighed_channel_2
    unit_of_measurement: '%'
    accuracy_decimals: 1
    device_class: humidity
    register_type: read
    address: 206
    filters:
      - multiply: 0.01 

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_2} dugpunkt"
    id: dugpunkt_channel_2
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: humidity
    register_type: read
    address: 207
    filters:
      - multiply: 0.01  
      
#########################
### SETPOINT REGISTER  ##
#########################
number:

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_2} temperatur setpunkt"
    id: temperatur_setpunkt_channel_2
    min_value: 10.0
    max_value: 30.0
    step: 0.5
    address: 219
    force_new_range: true
    use_write_multiple: true 
    multiply: 100  

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_2} ferie temperatur setpunkt"
    id: ferie_temperatur_setpunkt_channel_2
    min_value: 10.0
    max_value: 30.0
    step: 0.5
    address: 222
    force_new_range: true
    use_write_multiple: true 
    multiply: 100

#########################
#### INPUT REGISTER  ####
#########################
binary_sensor:

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "Fejl ${channel_2}"
    id: sentio_warning_channel_2
    register_type: read
    address: 201
    bitmask: 1      

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "Lav batteri ${channel_2}"
    id: sentio_battery_low_channel_2
    register_type: read
    address: 203
    bitmask: 1 

#########################
#### CLIMATE ENTITY   ###
#########################
climate:
  - platform: sentio
    name: ${channel_2}
    current_temp_sensor_id: temperatur_channel_2
    target_temp_sensor_id: temperatur_setpunkt_channel_2
    mode_select_id: mode_channel_2