select:
  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_3} termostat lås"
    id: thermostat_lock_channel_3
    address: 320
    force_new_range: true
    use_write_multiple: true
    value_type: U_WORD
    optionsmap:
      "Locked" : 8
      "Hotel" : 16
      "Unlocked" : 32
      
#########################
#### INPUT REGISTER  ####
#########################
sensor:

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_3} mode"
    id: mode_channel_3
    register_type: read
    address: 302
      
  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_3} temperatur"
    id: temperatur_channel_3
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    register_type: read
    address: 304
    filters:
      - multiply: 0.01
      
  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_3} luftfugtighed"
    id: luftfugtighed_channel_3
    unit_of_measurement: '%'
    accuracy_decimals: 1
    device_class: humidity
    register_type: read
    address: 306
    filters:
      - multiply: 0.01 

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_3} dugpunkt"
    id: dugpunkt_channel_3
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: humidity
    register_type: read
    address: 307
    filters:
      - multiply: 0.01  
      
#########################
### SETPOINT REGISTER  ##
#########################
number:

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_3} temperatur setpunkt"
    id: temperatur_setpunkt_channel_3
    min_value: 10.0
    max_value: 30.0
    step: 0.5
    address: 319
    force_new_range: true
    use_write_multiple: true 
    multiply: 100  

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_3} ferie temperatur setpunkt"
    id: ferie_temperatur_setpunkt_channel_3
    min_value: 10.0
    max_value: 30.0
    step: 0.5
    address: 322
    force_new_range: true
    use_write_multiple: true 
    multiply: 100

#########################
#### INPUT REGISTER  ####
#########################
binary_sensor:

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "Fejl ${channel_3}"
    id: sentio_warning_channel_3
    register_type: read
    address: 301
    bitmask: 1      

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "Lav batteri ${channel_3}"
    id: sentio_battery_low_channel_3
    register_type: read
    address: 303
    bitmask: 1 

#########################
#### CLIMATE ENTITY   ###
#########################
climate:
  - platform: sentio
    name: ${channel_3}
    current_temp_sensor_id: temperatur_channel_3
    target_temp_sensor_id: temperatur_setpunkt_channel_3
    mode_select_id: mode_channel_3