select:
  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_6} termostat lås"
    id: thermostat_lock_channel_6
    address: 620
    force_new_range: true
    use_write_multiple: true
    value_type: U_WORD
    optionsmap:
      "Locked" : 8
      "Hotel" : 16
      "Unlocked" : 32
      
#########################
#### INPUT REGISTER  ####
#########################
sensor:

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_6} mode"
    id: mode_channel_6
    register_type: read
    address: 602
      
  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_6} temperatur"
    id: temperatur_channel_6
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    register_type: read
    address: 604
    filters:
      - multiply: 0.01
      
  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_6} luftfugtighed"
    id: luftfugtighed_channel_6
    unit_of_measurement: '%'
    accuracy_decimals: 1
    device_class: humidity
    register_type: read
    address: 606
    filters:
      - multiply: 0.01 

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_6} dugpunkt"
    id: dugpunkt_channel_6
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: humidity
    register_type: read
    address: 607
    filters:
      - multiply: 0.01  
      
#########################
### SETPOINT REGISTER  ##
#########################
number:

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_6} temperatur setpunkt"
    id: temperatur_setpunkt_channel_6
    min_value: 10.0
    max_value: 30.0
    step: 0.5
    address: 619
    force_new_range: true
    use_write_multiple: true 
    multiply: 100  

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_6} ferie temperatur setpunkt"
    id: ferie_temperatur_setpunkt_channel_6
    min_value: 10.0
    max_value: 30.0
    step: 0.5
    address: 622
    force_new_range: true
    use_write_multiple: true 
    multiply: 100

#########################
#### INPUT REGISTER  ####
#########################
binary_sensor:

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "Fejl ${channel_6}"
    id: sentio_warning_channel_6
    register_type: read
    address: 601
    bitmask: 1      

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "Lav batteri ${channel_6}"
    id: sentio_battery_low_channel_6
    register_type: read
    address: 603
    bitmask: 1 

#########################
#### CLIMATE ENTITY   ###
#########################
climate:
  - platform: sentio
    name: ${channel_6}
    current_temp_sensor_id: temperatur_channel_6
    target_temp_sensor_id: temperatur_setpunkt_channel_6
    mode_select_id: mode_channel_6