select:
  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_13} termostat lås"
    id: thermostat_lock_channel_13
    address: 1320
    force_new_range: true
    use_write_multiple: true
    value_type: U_WORD
    optionsmap:
      "Locked" : 8
      "Hotel" : 16
      "Unlocked" : 32
      
#########################
#### INPUT REGISTER  ####
#########################
sensor:

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_13} mode"
    id: mode_channel_13
    register_type: read
    address: 1302
      
  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_13} temperatur"
    id: temperatur_channel_13
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    register_type: read
    address: 1304
    filters:
      - multiply: 0.01
      
  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_13} luftfugtighed"
    id: luftfugtighed_channel_13
    unit_of_measurement: '%'
    accuracy_decimals: 1
    device_class: humidity
    register_type: read
    address: 1306
    filters:
      - multiply: 0.01 

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_13} dugpunkt"
    id: dugpunkt_channel_13
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: humidity
    register_type: read
    address: 1307
    filters:
      - multiply: 0.01  
      
#########################
### SETPOINT REGISTER  ##
#########################
number:

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_13} temperatur setpunkt"
    id: temperatur_setpunkt_channel_13
    min_value: 10.0
    max_value: 30.0
    step: 0.5
    address: 1319
    force_new_range: true
    use_write_multiple: true 
    multiply: 100  

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_13} ferie temperatur setpunkt"
    id: ferie_temperatur_setpunkt_channel_13
    min_value: 10.0
    max_value: 30.0
    step: 0.5
    address: 1322
    force_new_range: true
    use_write_multiple: true 
    multiply: 100

#########################
#### INPUT REGISTER  ####
#########################
binary_sensor:

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "Fejl ${channel_13}"
    id: sentio_warning_channel_13
    register_type: read
    address: 1301
    bitmask: 1      

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "Lav batteri ${channel_13}"
    id: sentio_battery_low_channel_13
    register_type: read
    address: 1303
    bitmask: 1 

#########################
#### CLIMATE ENTITY   ###
#########################
climate:
  - platform: sentio
    name: ${channel_13}
    current_temp_sensor_id: temperatur_channel_13
    target_temp_sensor_id: temperatur_setpunkt_channel_13
    mode_select_id: mode_channel_13