select:
  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_14} termostat lås"
    id: thermostat_lock_channel_14
    address: 1420
    force_new_range: true
    use_write_multiple: true
    value_type: U_WORD
    optionsmap:
      "Locked" : 8
      "Hotel" : 16
      "Unlocked" : 32
      
#########################
#### INPUT REGISTER  ####
#########################
sensor:

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_14} mode"
    id: mode_channel_14
    register_type: read
    address: 1402
      
  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_14} temperatur"
    id: temperatur_channel_14
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    register_type: read
    address: 1404
    filters:
      - multiply: 0.01
      
  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_14} luftfugtighed"
    id: luftfugtighed_channel_14
    unit_of_measurement: '%'
    accuracy_decimals: 1
    device_class: humidity
    register_type: read
    address: 1406
    filters:
      - multiply: 0.01 

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_14} dugpunkt"
    id: dugpunkt_channel_14
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: humidity
    register_type: read
    address: 1407
    filters:
      - multiply: 0.01  
      
#########################
### SETPOINT REGISTER  ##
#########################
number:

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_14} temperatur setpunkt"
    id: temperatur_setpunkt_channel_14
    min_value: 10.0
    max_value: 30.0
    step: 0.5
    address: 1419
    force_new_range: true
    use_write_multiple: true 
    multiply: 100  

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_14} ferie temperatur setpunkt"
    id: ferie_temperatur_setpunkt_channel_14
    min_value: 10.0
    max_value: 30.0
    step: 0.5
    address: 1422
    force_new_range: true
    use_write_multiple: true 
    multiply: 100

#########################
#### INPUT REGISTER  ####
#########################
binary_sensor:

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "Fejl ${channel_14}"
    id: sentio_warning_channel_14
    register_type: read
    address: 1401
    bitmask: 1      

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "Lav batteri ${channel_14}"
    id: sentio_battery_low_channel_14
    register_type: read
    address: 1403
    bitmask: 1 

#########################
#### CLIMATE ENTITY   ###
#########################
climate:
  - platform: sentio
    name: ${channel_14}
    current_temp_sensor_id: temperatur_channel_14
    target_temp_sensor_id: temperatur_setpunkt_channel_14
    mode_select_id: mode_channel_14