select:
  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_12} termostat lås"
    id: thermostat_lock_channel_12
    address: 1220
    force_new_range: true
    use_write_multiple: true
    value_type: U_WORD
    optionsmap:
      "Locked" : 8
      "Hotel" : 16
      "Unlocked" : 32
      
#########################
#### INPUT REGISTER  ####
#########################
sensor:

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_12} mode"
    id: mode_channel_12
    register_type: read
    address: 1202
      
  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_12} temperatur"
    id: temperatur_channel_12
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    register_type: read
    address: 1204
    filters:
      - multiply: 0.01
      
  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_12} luftfugtighed"
    id: luftfugtighed_channel_12
    unit_of_measurement: '%'
    accuracy_decimals: 1
    device_class: humidity
    register_type: read
    address: 1206
    filters:
      - multiply: 0.01 

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_12} dugpunkt"
    id: dugpunkt_channel_12
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: humidity
    register_type: read
    address: 1207
    filters:
      - multiply: 0.01  
      
#########################
### SETPOINT REGISTER  ##
#########################
number:

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_12} temperatur setpunkt"
    id: temperatur_setpunkt_channel_12
    min_value: 10.0
    max_value: 30.0
    step: 0.5
    address: 1219
    force_new_range: true
    use_write_multiple: true 
    multiply: 100  

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_12} ferie temperatur setpunkt"
    id: ferie_temperatur_setpunkt_channel_12
    min_value: 10.0
    max_value: 30.0
    step: 0.5
    address: 1222
    force_new_range: true
    use_write_multiple: true 
    multiply: 100

#########################
#### INPUT REGISTER  ####
#########################
binary_sensor:

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "Fejl ${channel_12}"
    id: sentio_warning_channel_12
    register_type: read
    address: 1201
    bitmask: 1      

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "Lav batteri ${channel_12}"
    id: sentio_battery_low_channel_12
    register_type: read
    address: 1203
    bitmask: 1 

#########################
#### CLIMATE ENTITY   ###
#########################
climate:
  - platform: sentio
    name: ${channel_12}
    current_temp_sensor_id: temperatur_channel_12
    target_temp_sensor_id: temperatur_setpunkt_channel_12
    mode_select_id: mode_channel_12