select:
  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_11} termostat lås"
    id: thermostat_lock_channel_11
    address: 1120
    force_new_range: true
    use_write_multiple: true
    value_type: U_WORD
    optionsmap:
      "Locked" : 8
      "Hotel" : 16
      "Unlocked" : 32
      
#########################
#### INPUT REGISTER  ####
#########################
sensor:

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_11} mode"
    id: mode_channel_11
    register_type: read
    address: 1102
      
  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_11} temperatur"
    id: temperatur_channel_11
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    register_type: read
    address: 1104
    filters:
      - multiply: 0.01
      
  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_11} luftfugtighed"
    id: luftfugtighed_channel_11
    unit_of_measurement: '%'
    accuracy_decimals: 1
    device_class: humidity
    register_type: read
    address: 1106
    filters:
      - multiply: 0.01 

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_11} dugpunkt"
    id: dugpunkt_channel_11
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: humidity
    register_type: read
    address: 1107
    filters:
      - multiply: 0.01  
      
#########################
### SETPOINT REGISTER  ##
#########################
number:

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_11} temperatur setpunkt"
    id: temperatur_setpunkt_channel_11
    min_value: 10.0
    max_value: 30.0
    step: 0.5
    address: 1119
    force_new_range: true
    use_write_multiple: true 
    multiply: 100  

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "${channel_11} ferie temperatur setpunkt"
    id: ferie_temperatur_setpunkt_channel_11
    min_value: 10.0
    max_value: 30.0
    step: 0.5
    address: 1122
    force_new_range: true
    use_write_multiple: true 
    multiply: 100

#########################
#### INPUT REGISTER  ####
#########################
binary_sensor:

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "Fejl ${channel_11}"
    id: sentio_warning_channel_11
    register_type: read
    address: 1101
    bitmask: 1      

  - platform: modbus_controller
    modbus_controller_id: sentio_modbus_controller
    name: "Lav batteri ${channel_11}"
    id: sentio_battery_low_channel_11
    register_type: read
    address: 1103
    bitmask: 1 

#########################
#### CLIMATE ENTITY   ###
#########################
climate:
  - platform: sentio
    name: ${channel_11}
    current_temp_sensor_id: temperatur_channel_11
    target_temp_sensor_id: temperatur_setpunkt_channel_11
    mode_select_id: mode_channel_11